<tr data-id="{{$message->id}}">
    <td>
        @include('components.tables.history.target_name')
    </td>
    <td>
        @include('components.tables.history.target_number') 
    </td>
    <td>
        @include('components.tables.history.target_message') 
    </td>
    <td>
        @include('components.tables.history.status') 
    </td>
    <td>
        @include('components.tables.history.received_at') 
    </td>
    <td>
        @include('components.tables.history.sent_at') 
    </td>
    <td>
        @include('components.tables.history.actions') 
    </td>
</tr>